#cosmosdecorations
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TheCosmicNebula/DimensionalPocketsII/issues"
logoFile="decor_logo.png"
	
[[mods]] #mandatory
	modId="cosmosdecorations"
	version="2.0.0.0"
	displayName="Cosmos Decorations"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cosmos-decorations"
	credits=""
	authors="TheCosmicNebula_"
	description='''
Adds lots of new decorative and useful blocks!
'''

[[dependencies.cosmosdecorations]]
    modId="cosmoslibrary"
    mandatory=true
    versionRange="[10.0.0.0,11)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.cosmosdecorations]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cosmosdecorations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21]"
    ordering="NONE"
    side="BOTH"